Repository mapbox/mapbox-gl-native-android, pull requests merged in 2019-12, with the labels that each got.

#86 Remove core benchmark trigger
  .circleci/config.yml
Labels: build

#87 Expose getter for the view used for rendering OpenGL
  CHANGELOG.md
  MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
  MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/RenderViewGetterTest.kt
Labels: enhancement

#110 [docs] 8.5.2 changelog release-sangria cherrypick to master
  CHANGELOG.md
Labels: documentation

#112 [buck] use buck to build library
  .circleci/config.yml
  core-files.json
  filesource-files.json
  misc/buck/.buckconfig
  misc/buck/mapbox-gl-native/Android.mk
  misc/buck/mapbox-gl-native/Application.mk
  misc/buck/mapbox-gl-native/BUCK
  misc/buck/mapbox-gl-native/include
  misc/buck/mapbox-gl-native/mapbox-gl-native
  misc/buck/mapbox-gl-native/platform
  misc/buck/mapbox-gl-native/sdk
  misc/buck/mapbox-gl-native/src
  misc/buck/mapbox-gl-native/vendor
  misc/buck/mapbox-gl-native/vendor-android
  version-script
Labels: build
