Repository mapbox/mapbox-gl-native-android, pull requests merged in 2020-05, with the labels that each got.

#382 Fix binary size.
  MapboxGLAndroidSDK/src/cpp/CMakeLists.txt
Labels: build

#381 CP: Reset AndroidRendererBackend properly
  MapboxGLAndroidSDK/src/cpp/map_renderer.cpp
Labels: needs cherrypick

#397 [ci] Test release build of the test app with robo on firebase.
  .circleci/config.yml
Labels: skip-changelog, tests
