Repository mapbox/mapbox-gl-native-android, pull requests merged in 2020-01, with the labels that each got.

#135 Update javadoc of setResourceCachePath
  MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/storage/FileSource.java
  MapboxGLAndroidSDKTestApp/src/main/AndroidManifest.xml
Labels: documentation

#125 Adjusted SNAPSHOT section of README
  README.md
Labels: documentation

#137 Update changelog for v8.6.1 patch release
  CHANGELOG.md
Labels: documentation

#146 Expose pixel ratio as public API on MapView
  MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
Labels: enhancement

#153 [docs] update changelog for v8.6.2
  CHANGELOG.md
Labels: documentation

#156 Expose disabling horizontall scroll gestures
  MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/constants/MapboxConstants.java
  MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapGestureDetector.java
  MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapboxMapOptions.java
  MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
  MapboxGLAndroidSDK/src/main/res-public/values/public.xml
  MapboxGLAndroidSDK/src/main/res/values/attrs.xml
  MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/MapboxMapOptionsTest.java
  MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
  MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/camera/GestureDetectorActivity.java
  MapboxGLAndroidSDKTestApp/src/main/res/menu/menu_gestures.xml
Labels: enhancement

#158 [docs] update changelog for v9.0.0-beta.1
  CHANGELOG.md
Labels: documentation

#155 [deps] update accounts library to 0.7.0
  gradle/dependencies.gradle
Labels: dependencies, release-blocker

#141 Lazy load view components in MapView.
  MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/MapView.java
  MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/UiSettings.java
  MapboxGLAndroidSDK/src/main/res/layout/mapbox_mapview_internal.xml
  MapboxGLAndroidSDK/src/test/java/com/mapbox/mapboxsdk/maps/UiSettingsTest.java
  MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/widgets/AttributionTest.java
  MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/widgets/CompassViewTest.java
  MapboxGLAndroidSDKTestApp/src/androidTest/java/com/mapbox/mapboxsdk/testapp/maps/widgets/LogoTest.java
Labels: enhancement
